


runtime: python38

instance_class: F1

env_variables:
  DJANGO_SETTINGS_MODULE: 'myproject.settings'
  # Adicione quaisquer outras variáveis ​​de ambiente que você precise aqui

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

entrypoint: gunicorn -b :$PORT wsgi.py:application
